Add 2 new class methods for generating an NxN DFT matrix and its inverse
supercollider-quarks/MathLib pull request #2
Opened 2016-10-29 12:25 UTC by michaeldzjap

I just added two class methods for generating an NxN DFT matrix and its inverse: [https://en.wikipedia.org/wiki/DFT_matrix](https://en.wikipedia.org/wiki/DFT_matrix). Would be nice if this could be integrated in the Matrix class.

Thanks.

2016-10-29 14:54 UTC, nhthn approved these changes
Implementation looks good, but it's up to the maintainers to decide whether they want this feature. Paging @telephon.

2016-10-29 18:27 UTC, telephon requested changes
just minor formatting issues. t would be good if you have an example that could be added to the help files.

2016-10-29 18:27 UTC, telephon commented on classes/various/Matrix.sc
> +		dft = sqrt(n).reciprocal*super.fill(n, { |r|
could you please add spaces between the operators? That is only a formatting conventions, but still ...

2016-10-29 18:27 UTC, telephon commented on classes/various/Matrix.sc
> +			Array.fill(n, { |c| Polar(1, 2pi*r*c/n) })
same here …

2016-10-30 09:23 UTC, michaeldzjap commented
I've made the requested modifications. I have also made a new .schelp file for Matrix based on the old .html help file and also added documentation for `*newDFT` and `*newIDFT` in there.

In addition, I have revised the help file for `RootFinder` (I am the original author of that class), so that it can be rendered again. I guess the `MATH::` tag got deprecated somewhere along the line, so just replaced it with `TELETYPE::`. So that open issue can be closed as well.

2016-10-30 17:51 UTC, telephon approved these changes
great! also, thanks a lot for converting the helpfile!

2016-10-30 17:51 UTC, merged