Quaternion: added conversion to Euler angles
supercollider-quarks/MathLib pull request #7
Opened 2019-11-16 01:20 UTC by dmartinp

From the math found [here](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Quaternion_to_Euler_Angles_Conversion), added Quaternion to Euler angle conversions. The `tumble` method is slightly hacky in two ways. One it clips the value to -1 to 1 to avoid `nan`s and second it attempts to do `atan2` to asin, where we can tell which quadrant we are in so we can know if we go above 0.5pi and below -0.5pi...

2019-12-09 09:09 UTC, telephon requested changes

2019-12-09 09:09 UTC, telephon commented on classes/various/Quaternion.sc
> +		case(
this case distinction can be replaced by:
```
ang = if(x.isNegative) { (pi - ang) * (x.sign * ang.sign) } { ang }
```

2019-12-09 09:09 UTC, telephon commented on classes/various/Quaternion.sc
> +		x = ((this.rotate < 0.5pi) and: (this.rotate > -0.5pi)).if({
it is much more efficient to enclose the part after the `and:` in curly brackets.

2019-12-09 09:12 UTC, telephon reviewed
Two more things: so far, `Quaternion` could be used in UGens:
```
a = Quaternion(LFNoise0.kr, LFNoise0.kr, LFNoise0.kr, LFNoise0.kr);
b = a * a;
```
Maybe you could refactor your change so that it works with UGens?
Also documentation is needed, but that can wait a little till the new help system is up.

2019-12-18 23:51 UTC, dmartinp commented
After looking at the requested changes, I dove into testing the math a bit more and it turns out that it is really difficult to get the behavior I was after with the `tumble` method. I have changed it to be less specific, which I think is better for all users.

It looks like these methods work fine with UGens...

2019-12-19 00:18 UTC, joslloand commented
@dmartinp when https://github.com/supercollider-quarks/MathLib/pull/12 is accepted, it would be good to add documentation to [Quaternion.schelp](https://github.com/supercollider-quarks/MathLib/blob/db68e39361cfb4f6b018f1a12a3e2a893f00b702/HelpSource/Classes/Quaternion.schelp)

... or... it could be that you might like to update this PR to include the requisite additions....

2019-12-19 00:29 UTC, dmartinp commented
@joslloand If I update #12 with the appropirate Quaternion methods in the help file, would that create a conflict if #12 is merged before #7 in that the help file would have methods that don't yet exist?

2019-12-19 00:43 UTC, joslloand commented
Most likely.... https://github.com/supercollider-quarks/MathLib/pull/12 would need to be accepted first.

2019-12-19 07:26 UTC, merged

2019-12-20 00:26 UTC, joslloand commented
@dmartinp ok, both of these PRs have been merged... feel free to add documentation to [Quaternion.schelp](https://github.com/supercollider-quarks/MathLib/blob/master/HelpSource/Classes/Quaternion.schelp)